#设置服务提供者tomcat的端口号
server:
  port: 8001

#设置连接数据库mysql的数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_jdbc?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      #此处指为update表示如果数据库中没有创建表，就创建表，如果有，只进行对表中的数据操作
      ddl-auto: update
    #表示在控制台展示sql语句
    show-sql: true
  #设置提供者部署在Eureka服务中心的应用名
  application:
    name: Provider

#设置默认连接eureka服务端的地址，如果有多个使用逗号分隔开
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
      
      
ProviderVersion: 服务提供者001---版本1.0--UpdateNewPLUSASAFSFS




